sudo: required

language: ruby

services:
  - docker

script: docker-compose up -d postgres && \
  docker-compose run --rm api rake && \
  docker-compose exec api /bundle/bin/brakeman

before_script:
  - docker-compose run --rm api bundle exec rails db:migrate
  - gem install brakeman
