# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - checkout

      - run:
          name: Start PG
          command: docker-compose up -d postgres

      - run:
          name: Execute Test Suite
          command: |
            docker-compose run --rm api bundle exec rails db:migrate
            docker-compose run --rm api rake

      - run:
          name: Brakeman
          command: docker run -v "$(pwd)":/code presidentbeef/brakeman --color
